const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  workspace: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Workspace',
    index: true,
  },
  date: {
    type: Date,
    required: true,
    index: true,
  },
  dateKey: {
    type: String,
    required: true,
    index: true, // Format: YYYY-MM-DD
  },
  checkInTime: {
    type: Date,
    default: null,
  },
  checkOutTime: {
    type: Date,
    default: null,
  },
  totalHours: {
    type: Number,
    default: 0,
  },
  status: {
    type: String,
    enum: ['present', 'late', 'absent', 'half-day', 'incomplete'],
    default: 'absent',
  },
  isLate: {
    type: Boolean,
    default: false,
  },
  lateMinutes: {
    type: Number,
    default: 0,
  },
  expectedCheckInTime: {
    type: String,
    default: '09:00', // 9 AM default
  },
  expectedCheckOutTime: {
    type: String,
    default: '18:00', // 6 PM default
  },
  checkInLocation: {
    lat: Number,
    lng: Number,
  },
  checkOutLocation: {
    lat: Number,
    lng: Number,
  },
  geofenceId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Geofence',
  },
  notes: {
    type: String,
    default: '',
  },
  autoGenerated: {
    type: Boolean,
    default: true,
  },
}, {
  timestamps: true,
});

// Compound index for efficient queries
attendanceSchema.index({ user: 1, dateKey: 1 }, { unique: true });
attendanceSchema.index({ workspace: 1, date: 1 });

// Calculate total hours when checkOutTime is set
attendanceSchema.pre('save', function(next) {
  if (this.checkInTime && this.checkOutTime) {
    const diffMs = this.checkOutTime - this.checkInTime;
    this.totalHours = Math.round((diffMs / (1000 * 60 * 60)) * 100) / 100; // Round to 2 decimal places
  }

  // Determine if late
  if (this.checkInTime) {
    const expectedTime = new Date(this.checkInTime);
    const [hours, minutes] = this.expectedCheckInTime.split(':');
    expectedTime.setHours(parseInt(hours), parseInt(minutes), 0, 0);

    if (this.checkInTime > expectedTime) {
      this.isLate = true;
      this.lateMinutes = Math.round((this.checkInTime - expectedTime) / (1000 * 60));
    }
  }

  next();
});

module.exports = mongoose.model('Attendance', attendanceSchema);