const Attendance = require('../models/Attendance');
const User = require('../models/User');
const attendanceService = require('../services/attendanceService');
const Workspace = require('../models/Workspace');

const canAccessWorkspace = async ({ actor, workspaceId }) => {
  if (actor.role === 'superadmin') {
    return true;
  }

  const actorWorkspaceId = actor.workspace?._id?.toString?.() || actor.workspace?.toString?.() || '';
  if (actorWorkspaceId && actorWorkspaceId === String(workspaceId)) {
    return true;
  }

  if (actor.role === 'admin') {
    const workspace = await Workspace.findById(workspaceId);
    return Boolean(workspace && String(workspace.owner) === String(actor._id));
  }

  return false;
};

// Get attendance records for a user
exports.getUserAttendance = async (req, res) => {
  try {
    const { userId } = req.params;
    const { startDate, endDate } = req.query;

    // Check if user can access this data (own data or admin)
    if (req.user.id !== userId && req.user.role !== 'admin' && req.user.role !== 'superadmin') {
      return res.status(403).json({ message: 'Access denied' });
    }

    const attendance = await attendanceService.getUserAttendance(userId, startDate, endDate);
    res.json(attendance);
  } catch (error) {
    console.error('Error fetching user attendance:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get attendance summary for a workspace
exports.getWorkspaceAttendanceSummary = async (req, res) => {
  try {
    const { workspaceId } = req.params;
    const { date } = req.query;

    // Check if user belongs to this workspace or is admin
    const user = await User.findById(req.user.id).populate('workspace', 'name');
    if (!(await canAccessWorkspace({ actor: user, workspaceId }))) {
      return res.status(403).json({ message: 'Access denied' });
    }

    const summary = await attendanceService.getWorkspaceAttendanceSummary(workspaceId, date ? new Date(date) : null);
    res.json(summary);
  } catch (error) {
    console.error('Error fetching workspace attendance summary:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Manual check-in/check-out (for admin override)
exports.manualAttendanceUpdate = async (req, res) => {
  try {
    const { userId, date, checkInTime, checkOutTime, notes } = req.body;

    // Only admins can manually update attendance
    if (req.user.role !== 'admin' && req.user.role !== 'superadmin') {
      return res.status(403).json({ message: 'Access denied' });
    }

    const targetDate = new Date(date);
    const dateKey = targetDate.toISOString().split('T')[0];

    let attendance = await Attendance.findOne({
      user: userId,
      dateKey: dateKey,
    });

    if (!attendance) {
      attendance = new Attendance({
        user: userId,
        date: targetDate,
        dateKey: dateKey,
        autoGenerated: false,
      });
    }

    if (checkInTime) {
      attendance.checkInTime = new Date(checkInTime);
    }

    if (checkOutTime) {
      attendance.checkOutTime = new Date(checkOutTime);
    }

    if (notes) {
      attendance.notes = notes;
    }

    await attendance.save();
    res.json(attendance);
  } catch (error) {
    console.error('Error updating attendance manually:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Mark absentees for a specific date
exports.markAbsentees = async (req, res) => {
  try {
    const { workspaceId, date } = req.body;

    // Only admins can mark absentees
    if (req.user.role !== 'admin' && req.user.role !== 'superadmin') {
      return res.status(403).json({ message: 'Access denied' });
    }

    const absentees = await attendanceService.markAbsenteesForDate(workspaceId, new Date(date));
    res.json({ message: `Marked ${absentees.length} employees as absent`, absentees });
  } catch (error) {
    console.error('Error marking absentees:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Update attendance settings for a workspace
exports.updateAttendanceSettings = async (req, res) => {
  try {
    const { workspaceId } = req.params;
    const settings = req.body;

    // Check if user is workspace admin or superadmin
    const user = await User.findById(req.user.id).populate('workspace', 'name');
    if (!(await canAccessWorkspace({ actor: user, workspaceId }))) {
      return res.status(403).json({ message: 'Access denied' });
    }

    const updatedSettings = await attendanceService.updateWorkspaceAttendanceSettings(workspaceId, settings);
    res.json(updatedSettings);
  } catch (error) {
    console.error('Error updating attendance settings:', error);
    res.status(500).json({ message: 'Server error' });
  }
};

// Get attendance statistics
exports.getAttendanceStats = async (req, res) => {
  try {
    const { workspaceId } = req.params;
    const { startDate, endDate } = req.query;

    // Check access
    const user = await User.findById(req.user.id).populate('workspace', 'name');
    if (!(await canAccessWorkspace({ actor: user, workspaceId }))) {
      return res.status(403).json({ message: 'Access denied' });
    }

    const start = startDate ? new Date(startDate) : new Date(Date.now() - 30 * 24 * 60 * 60 * 1000); // 30 days ago
    const end = endDate ? new Date(endDate) : new Date();

    const attendanceRecords = await Attendance.find({
      workspace: workspaceId,
      date: { $gte: start, $lte: end },
    }).populate('user', 'name email');

    // Calculate statistics
    const stats = {
      totalRecords: attendanceRecords.length,
      present: attendanceRecords.filter(r => r.status === 'present').length,
      late: attendanceRecords.filter(r => r.status === 'late').length,
      absent: attendanceRecords.filter(r => r.status === 'absent').length,
      halfDay: attendanceRecords.filter(r => r.status === 'half-day').length,
      averageHours: 0,
      totalLateMinutes: 0,
    };

    const recordsWithHours = attendanceRecords.filter(r => r.totalHours > 0);
    if (recordsWithHours.length > 0) {
      stats.averageHours = recordsWithHours.reduce((sum, r) => sum + r.totalHours, 0) / recordsWithHours.length;
    }

    stats.totalLateMinutes = attendanceRecords.reduce((sum, r) => sum + (r.lateMinutes || 0), 0);

    res.json(stats);
  } catch (error) {
    console.error('Error fetching attendance stats:', error);
    res.status(500).json({ message: 'Server error' });
  }
};
